### PR TITLE
update json files for PR #41 changes

### PR DESCRIPTION
**Pull request by jreadey**
JSON data file updates

### CODE REVIEW

**Comment by jreadey** [comment]
@ajelenak-thg - take a look at this. There are a couple of cases (e.g. compound.json) where PR #41 seems to have incorrectly removed that fill values.

**Comment by ajelenak-thg** [comment]
@jreadey Was compound.json generated from compound.h5? In compound.json, the /dset's fill value is:
```json
                "fillValue": [
                    999, 
                    "99:90", 
                    999, 
                    999.0, 
                    "N"
                ]
```
but `h5dump -p -A ../data/hdf5/compound.h5` reports a different fill value:
```
      FILLVALUE {
         VALUE  {
            0,
            "\000\000\000\000\000\000",
            0,
            0,
            "\000\000\000\000\000\000"
         }
      }
```

**Comment by jreadey** [comment]
I'm not sure.  But if I convert the old json (with fill values) to hdf5 and the hdf5 back to json it retains the fill value.  I'll revert the json/compound.json and update the hdf5/compound.h5 files.

**Comment by jreadey** [comment]
PR is updated.

**Comment by ajelenak-thg** [comment]
@jreadey Are there any other issues? Is this PR ready for merging?

**Comment by jreadey** [comment]
Yes, I've merged.

**Pull request merged**
