### PR TITLE
Two fixes

### PR DESCRIPTION
**Pull request by ajelenak-thg**

### CODE REVIEW

**Comment by jreadey** [comment]
Aleksandar, 
Can you sync with the latest changes?  You have a bunch of whitespace edits that will make it hard to merge.

**Comment by jreadey** [comment]
Also I added a test case: hdf5dbTest/testCreate2dExtendableDataset.

**Comment by ajelenak-thg** [comment]
@jreadey It is unfortunate there is a mismatch in the treatment of extraneous whitespace between our text editors. The merge conflict was only one line of code.

How about now? There real code [changes](https://github.com/HDFGroup/hdf5-json/pull/28/files) are not any more obscured by all that whitespace difference.

**Comment by jreadey** [comment]
Yes, that's much better.

**Pull request merged**
